apiVersion: v1
kind: Pod
metadata:
  name: download-llama-70b
  namespace: disagg-1-1
  annotations:
    gke-gcsfuse/volumes: "true"
    gke-gcsfuse/cpu-limit: "0"
    gke-gcsfuse/memory-limit: "0"
    gke-gcsfuse/ephemeral-storage-limit: "0"
spec:
  containers:
  - name: downloader
    image: vllm/vllm-openai:latest
    command: ["/bin/bash", "-c"]
    args:
    - |
      huggingface-cli login --token $HF_TOKEN
      huggingface-cli download meta-llama/Llama-3.1-70B-Instruct --local-dir /models/hf-models/Llama-3.1-70B-Instruct
    env:
    - name: HF_TOKEN
      value: "<HF_TOKEN>"
    volumeMounts:
    - mountPath: /models
      name: model-volume
  volumes:
  - csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: rlalwani-vllm
        mountOptions: "implicit-dirs"
    name: model-volume
  restartPolicy: Never
