apiVersion: v1
kind: Service
metadata:
  name: qwen3-prefill-service
spec:
  selector:
    llm-d.ai/model: Qwen3-32B
    llm-d.ai/role: prefill
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
  type: ClusterIP
