export PROJECT_ID=xprof-plugin-project
export CLUSTER=vllm-dev-cluster
export LOCATION=us-central1
export ZONE=us-central1-b
export RESERVATION=
export VPC_NETWORK_NAME=default
export SUBNET_NAME=proxy-only-subnet
export NODE_POOL=tpuv6enodepool
export NETWORK_FW_NAME=gke-gateway-firewall-${CLUSTER}-${NODE_POOL}
export MACHINE_TYPE=ct6e-standard-8t
export CIDR_RANGE=172.16.0.0/26 # ATTN: Make sure the IP range does not overlap with other subnets!!!
export NAMESPACE=llm-d-pd
export HF_TOKEN=
